run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - misspell
    - bodyclose
    - gocritic
    - gosec

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

linters-settings:
  goimports:
    local-prefixes: github.com/loglens/loglens
  revive:
    rules:
      - name: exported
        arguments: ["disableStutteringCheck"]
